### ISSUE TITLE
media query for different screen sizes

### ISSUE THREAD

**Issue by Flipper5001** [Flipper5001/project1#26]

**Comment by maytiara** [comment]
From top to bottom changes:

- Add new section for Header-text holder> <span> & add animation & change style.

        <span class="header-sub">
            
            <h3 class="grid-margin-y" id="header-txt">Hey, I'm chef Sam, happy to help...</h3>
        </span>

- changed the main-img [see may-dev assets folder] > vector-man-scratching-head-01.png

**Comment by maytiara** [comment]
Results: 

![Image](https://user-images.githubusercontent.com/52232162/176123745-963be4d2-20c6-4910-a86f-bd8d086ac56c.jpg)

** RESULT: Media queries
/* Small only */

media screen and (max-width: 39.9375em)**
